Longo_tp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("inicio.urls")),
    path("productos/", include("productos.urls")),
    path("usuarios/", include("usuarios.urls")),
]   

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inicio/urls.py
from django.urls import path
from inicio.views import (
    inicio,
    buscar_pesa, 
    crear_pesa,
    acerca_de_mi,
    ver_pesa,
    eliminar_pesa,
    editar_pesa
)
app_name = "inicio"

urlpatterns = [
    path("", inicio, name="inicio"),
    path("buscar-pesa/", buscar_pesa, name="buscar_pesa"),
    path("crear-pesa/", crear_pesa, name="crear_pesa"),
    path("acerca-de-mi/", acerca_de_mi, name="acerca_de_mi"),
    path("ver-pesa/", ver_pesa, name="ver_pesa"),
    path("ver-pesa/<int:id>/", ver_pesa, name="ver_pesa"),
    path("eliminar-pesa/<int:id>/", eliminar_pesa, name="eliminar_pesa"),
    path("editar-pesa/<int:id>/", editar_pesa, name="editar_pesa"),
]




   

inicio/models.py
from django.db import models


class Pesas(models.Model):
    marca = models.CharField(max_length=20)
    material = models.CharField(max_length=20)
    peso = models.IntegerField()


    def __str__(self):
        return f"{self.marca} {self.peso}"
    

inicio/forms.py
from django import forms

class PesaFormularioBase(forms.Form):
    marca = forms.CharField(max_length=20)
    material = forms.CharField(max_length=20)
    peso = forms.IntegerField()

class CrearPesaFormulario(PesaFormularioBase):...
   
class EditarPesaFormulario(PesaFormularioBase):...
    

class BuscarPesaFormulario(forms.Form):
    marca = forms.CharField(max_length=20, required=False)

inicio/views.py
from django.http import HttpResponse
from django.template import Template, Context, loader
from datetime import datetime
from django.shortcuts import render, redirect
from inicio.models import Pesas 
from inicio.forms import CrearPesaFormulario, BuscarPesaFormulario, EditarPesaFormulario
from django.contrib.auth.decorators import login_required

def inicio(request):
    return render(request, "inicio/index.html")

def acerca_de_mi(request):

    archivo_del_template = open(r"templates\acerca_de_mi.html")
    template = Template(archivo_del_template.read())
    archivo_del_template.close()
    contexto = Context()

    render_template = template.render(contexto)

    return HttpResponse(render_template) 

def buscar_pesa(request):

    formulario = BuscarPesaFormulario(request.GET)
    if formulario.is_valid():
        marca = formulario.cleaned_data.get("marca") 
        pesas = Pesas.objects.filter(marca__icontains=marca)

    return render(request, "inicio/buscar_pesa.html", {"pesas": pesas, "form": formulario})

def crear_pesa(request):

    formulario = CrearPesaFormulario()

    if request.method == "POST":
  
        formulario = CrearPesaFormulario(request.POST)
        if formulario.is_valid(): 
            data = formulario.cleaned_data 
            pesa = Pesas(marca=data.get("marca"), material=data.get("material"), peso=data.get("peso"))
            pesa.save()
            return redirect("inicio:buscar_pesa") 

    return render(request, "inicio/crear_pesa.html", {"form": formulario})


def ver_pesa(request, id):
    pesa = Pesas.objects.get(id=id)
    return render(request, "inicio/ver_pesa.html", {"pesa": pesa})

@login_required
def eliminar_pesa(request, id):
    pesa = Pesas.objects.get(id=id)
    pesa.delete()
    return redirect("inicio:buscar_pesa")
@login_required
def editar_pesa(request, id):
    pesa = Pesas.objects.get(id=id)

    formulario = EditarPesaFormulario(initial={"material": pesa.material, "marca": pesa.marca, "peso": pesa.peso})

    if request.method == "POST":
        formulario = EditarPesaFormulario(request.POST)
        if formulario.is_valid():
            pesa.material = formulario.cleaned_data.get("material")
            pesa.marca = formulario.cleaned_data.get("marca")
            pesa.peso = formulario.cleaned_data.get("peso")

            pesa.save()

            return redirect("inicio:buscar_pesa")
    return render(request, "inicio/editar_pesa.html", {"pesa": pesa, "form": formulario})

inicio/templates/inicio/buscar_pesa.html
{% extends "inicio/index.html" %}
{% load static %}
{% block title_head %}
Buscar Pesa
{% endblock title_head %}
{% block h1_header %}buscar pesa{% endblock h1_header %}
{% block main %}

<form action={% url "inicio:buscar_pesa" %}>
    {{form}}
    <input type="submit">
</form>

{% if pesas %}
<ul>
    {% for pesa in pesas %}
    <li>{{pesa}}
        | <a href={% url "inicio:ver_pesa" pesa.id %}>Ver mas</a> 
        | <a href={% url "inicio:editar_pesa" pesa.id %}>Editar</a> 
        | <a href={% url "inicio:eliminar_pesa" pesa.id %}>Eliminar</a> 
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No hay pesas registradas.</p>
{% endif %}

{% endblock main %}

inicio/templates/inicio/creacion_pesa.html
{% extends "base.html" %}

{% block title_head %}
creacion de pesa
{% endblock title_head %}

{% block h1_header %}
se creo la pesa {{pesa.id}} {{pesa.marca}} correctamente!
{% endblock h1_header %}
        

inicio/templates/inicio/crear_pesa.html
{% extends "inicio/index.html" %}
{% load static %}
{% block title_head %}
Crear Pesa
{% endblock title_head %}
{% block h1_header %}Crear Pesa{% endblock h1_header %}
{% block main %}

<form action={% url "inicio:crear_pesa" %} method="POST">
    {% csrf_token %}
    
    {{form}}  

    <input type="Submit" value="Enviar">    
</form>


{% endblock main %}

inicio/templates/inicio/editar_pesa.html
{% extends "inicio/index.html" %}
{% block title_head %}
Editar Pesa
{% endblock title_head %}
{% block h1_header %}Editar Pesa{% endblock h1_header %}
{% block main %}

<form action={% url "inicio:editar_pesa" pesa.id %} method="POST">
    {% csrf_token %}
    {{form}}  

    <input type="Submit" value="Enviar">    
</form>


{% endblock main %}

inicio/templates/inicio/index.html
{% extends "base.html" %}

{% block title_head %}
inicio
{% endblock title_head %}

{% block h1_header %}
Fitness Work
{% endblock h1_header %}

inicio/templates/inicio/segundo_template.html
{% extends "inicio/index.html" %}
{% load static %}
{% block h1_header %}segundo template{% endblock h1_header %}

{% block main %}
<h1>{{fecha_actual}}</h1>
<p>
    
</p>
{% endblock main %}

inicio/templates/inicio/ver_pesa.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Ver pesa
{% endblock title_head %}
{% block h1_header %}{{pesa}}{% endblock h1_header %}
{% block main %}
<ul>
    <li>Marca: {{pesa.marca}}</li> 
    <li>Material: {{pesa.material}}</li>
    <li>Peso: {{pesa.peso}}</li>   
</ul>    
{% endblock main%}