Longo_tp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("inicio.urls")),
    path("productos/", include("productos.urls")),
    path("usuarios/", include("usuarios.urls")),
]   

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inicio/urls.py
from django.urls import path
from inicio.views import (
    inicio,
    buscar_pesa, 
    crear_pesa,
    acerca_de_mi,
    ver_pesa,
    eliminar_pesa,
    editar_pesa
)
app_name = "inicio"

urlpatterns = [
    path("", inicio, name="inicio"),
    path("buscar-pesa/", buscar_pesa, name="buscar_pesa"),
    path("crear-pesa/", crear_pesa, name="crear_pesa"),
    path("acerca-de-mi/", acerca_de_mi, name="acerca_de_mi"),
    path("ver-pesa/", ver_pesa, name="ver_pesa"),
    path("ver-pesa/<int:id>/", ver_pesa, name="ver_pesa"),
    path("eliminar-pesa/<int:id>/", eliminar_pesa, name="eliminar_pesa"),
    path("editar-pesa/<int:id>/", editar_pesa, name="editar_pesa"),
]




   

productos/urls.py
from django.urls import path
from productos import views

app_name = "productos"

urlpatterns = [
    path("barras/", views.ListadoBarras.as_view(), name="listado_barras"),
    path("barras/crear/", views.CrearBarra.as_view(), name="crear_barra"),
    path("barras/<int:pk>/", views.VerBarra.as_view(), name="ver_barra"),
    path("barras/<int:pk>/editar/", views.EditarBarra.as_view(), name="editar_barra"),
    path("barras/<int:pk>/eliminar/", views.EliminarBarra.as_view(), name="eliminar_barra"),
]

productos/models.py
from django.db import models

class Barra(models.Model):
    marca = models.CharField(max_length=20)
    modelo = models.CharField(max_length=20)
    peso = models.IntegerField()

    def __str__(self):
        return f"{self.id} {self.modelo}"

productos/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from productos.models import Barra
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin


class CrearBarra(CreateView):
    model = Barra
    template_name = "productos/crear_barra.html"
    success_url = reverse_lazy("productos:listado_barras")
    fields = ["modelo", "marca", "peso"]

class ListadoBarras(ListView):
    model = Barra
    template_name = "productos/listado_barras.html"
    context_object_name = "barras"

class VerBarra(DetailView):
    model = Barra
    template_name = "productos/ver_barra.html"

class EditarBarra(LoginRequiredMixin, UpdateView):
    model = Barra
    template_name = reverse_lazy("productos/editar_barra.html")
    success_url = ["modelo", "marca", "peso"]

class EliminarBarra(LoginRequiredMixin, DeleteView):
    model = Barra
    template_name = "productos/eliminar_barra.html"
    success_url = reverse_lazy("productos:listado_barras")

productos/templates/productos/crear_barra.html
{% extends "base.html" %}
{% block title_head %}
Crear Barra
{% endblock title_head %}
{% block h1_header %}Crear Barra{% endblock h1_header %}
{% block main %}

<form action={% url "productos:crear_barra" %} method="POST">
    {% csrf_token %}
    {{form}}  

    <input type="Submit" value="Crear">    
</form>


{% endblock main %}

productos/templates/productos/editar_barra.html
{% extends "base.html" %}
{% block title_head %}
Editar Barra
{% endblock title_head %}
{% block h1_header %}Editar Barra{% endblock h1_header %}
{% block main %}

<form action={% url "productos:editar_barra" barra.id %} method="POST">
    {% csrf_token %}
    {{form}}  

    <input type="Submit" value="Editar">    
</form>


{% endblock main %}

productos/templates/productos/eliminar_barra.html
{% extends "base.html" %}
{% load static %}
{% block title_head %}
Eliminar Barra
{% endblock title_head %}
{% block h1_header %}Eliminar Barra{% endblock h1_header %}
{% block main %}

<form action={% url "productos:eliminar_barra" barra.id %} method="POST">
    {% csrf_token %}
    <P>Desea eliminar la barra {{barra}}?</p> 

    <input type="Submit" value="Confirmar">    
</form>


{% endblock main %}

productos/templates/productos/listado_barras.html
{% extends "base.html" %}
{% block title_head %}
Listado Barras
{% endblock title_head %}
{% block h1_header %}Listado Barras{% endblock h1_header %}
{% block main %}

<a class="navbar-brand" href={% url "productos:crear_barra" %}>Nueva Barra</a>

{% if barras %}
<ul>
    {% for barra in barras %}
    <li>{{barra}}
        | <a href={% url "productos:ver_barra" barra.id %}>Ver mas</a> 
        | <a href={% url "productos:editar_barra" barra.id %}>Editar</a> 
        | <a href={% url "productos:eliminar_barra" barra.id %}>Eliminar</a> 
    </li> 
    {% endfor %}
</ul>
{% else %}
<p>No hay barras registradas.</p>
{% endif %}

{% endblock main %}

productos/templates/productos/ver_barra.html
{% extends "base.html" %}
{% block title_head %}
Ver Barra
{% endblock title_head %}
{% block h1_header %}{{barra}}{% endblock h1_header %}
{% block main %}
<ul>
    <li>Marca: {{barra.marca}}</li> 
    <li>Modelo: {{barra.modelo}}</li>
    <li>Peso: {{barra.peso}}</li>   
</ul>    
{% endblock main%}