Longo_tp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("inicio.urls")),
    path("productos/", include("productos.urls")),
    path("usuarios/", include("usuarios.urls")),
]   

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inicio/urls.py
from django.urls import path
from inicio.views import (
    inicio,
    buscar_pesa, 
    crear_pesa,
    acerca_de_mi,
    ver_pesa,
    eliminar_pesa,
    editar_pesa
)
app_name = "inicio"

urlpatterns = [
    path("", inicio, name="inicio"),
    path("buscar-pesa/", buscar_pesa, name="buscar_pesa"),
    path("crear-pesa/", crear_pesa, name="crear_pesa"),
    path("acerca-de-mi/", acerca_de_mi, name="acerca_de_mi"),
    path("ver-pesa/", ver_pesa, name="ver_pesa"),
    path("ver-pesa/<int:id>/", ver_pesa, name="ver_pesa"),
    path("eliminar-pesa/<int:id>/", eliminar_pesa, name="eliminar_pesa"),
    path("editar-pesa/<int:id>/", editar_pesa, name="editar_pesa"),
]




   

productos/urls.py
from django.urls import path
from productos import views

app_name = "productos"

urlpatterns = [
    path("barras/", views.ListadoBarras.as_view(), name="listado_barras"),
    path("barras/crear/", views.CrearBarra.as_view(), name="crear_barra"),
    path("barras/<int:pk>/", views.VerBarra.as_view(), name="ver_barra"),
    path("barras/<int:pk>/editar/", views.EditarBarra.as_view(), name="editar_barra"),
    path("barras/<int:pk>/eliminar/", views.EliminarBarra.as_view(), name="eliminar_barra"),
]

usuarios/urls.py
from django.urls import path
from usuarios import views
from django.contrib.auth.views import LogoutView

app_name = "usuarios"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("perfil/editar/", views.editar_perfil, name="editar_perfil"),
    path("perfil/editar/password/", views.CambiarPassword.as_view(), name="cambiar_password"),
    path("logout/", LogoutView.as_view(template_name="usuarios/logout.html"), name="logout"),
]    

templates/acerca_de_mi.html
{% extends "base.html" %}

{% block title_head %}
Acerca de mi
{% endblock title_head %}

{% block h1_header %}
Informacion Personal
{% endblock h1_header %}

{% block main %}
<h1>
    Bienvenidos a mi sitio web!! mi nombre es Lorenzo Longo tengo 26 anios y siempre me gusto mucho la actividad fisica pase por casi todos los deportes, soy personal trainer y entreno hace 6 anios en el gym.   
</h1>
{% endblock main %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title_head %}
            template base
            {% endblock title_head %}
        </title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        {% block link_stylesheet_head %}
        <link href={%static "css/styles.css"%} rel="stylesheet" />
        {% endblock link_stylesheet_head %}
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav"> 
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href={% url "inicio:inicio" %}>Inicio</a>
                <a class="navbar-brand" href={% url "inicio:buscar_pesa" %}>Buscar Pesa</a>
                <a class="navbar-brand" href={% url "inicio:crear_pesa" %}>Crear Pesa</a>
                <a class="navbar-brand" href={% url "inicio:acerca_de_mi" %}>Acerca de mi</a>
                <a class="navbar-brand" href={% url "productos:listado_barras" %}>Barras</a>
                {% if request.user.is_authenticated %}
                <a class="navbar-brand" href={% url "usuarios:editar_perfil" %}>
                    <img src={{request.user.datosextra.avatar.url}} alt="" height="40px">
                    {{request.user.username}}
                </a>
                <form action={% url "usuarios:logout" %} method="POST">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-secondary" value="Cerrar Sesion">
                </form>
                {% else %}
                <a class="btn btn-dark" href={% url "usuarios:login" %}>Iniciar sesion</a>
                <a class="btn btn-light" href={% url "usuarios:register" %}>Registrarse</a>
                {% endif %}  
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#projects">Projects</a></li>
                        <li class="nav-item"><a class="nav-link" href="#signup">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
         {% block header %}
        <header class="masthead">
            <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
                <div class="d-flex justify-content-center">
                    <div class="text-center">
                        <h1 class="mx-auto my-0 text-uppercase">
                            {% block h1_header %}soy el base{% endblock h1_header %}
                            </h1>
                        <h2 class="text-white-50 mx-auto mt-2 mb-5">NO PAIN NO GAIN</h2>
                    </div>
                </div>
            </div>
        </header>
        {% endblock header %}
        <main>
        {% block main %}{% endblock main %}
        </main>
        <!-- Footer-->
        <footer class="footer bg-black small text-center text-white-50"><div class="container px-4 px-lg-5">Copyright &copy; Your Website 2023</div></footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static "js/scripts.js" %}></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>
 