Longo_tp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("inicio.urls")),
    path("productos/", include("productos.urls")),
    path("usuarios/", include("usuarios.urls")),
]   

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inicio/urls.py
from django.urls import path
from inicio.views import (
    inicio,
    buscar_pesa, 
    crear_pesa,
    acerca_de_mi,
    ver_pesa,
    eliminar_pesa,
    editar_pesa
)
app_name = "inicio"

urlpatterns = [
    path("", inicio, name="inicio"),
    path("buscar-pesa/", buscar_pesa, name="buscar_pesa"),
    path("crear-pesa/", crear_pesa, name="crear_pesa"),
    path("acerca-de-mi/", acerca_de_mi, name="acerca_de_mi"),
    path("ver-pesa/", ver_pesa, name="ver_pesa"),
    path("ver-pesa/<int:id>/", ver_pesa, name="ver_pesa"),
    path("eliminar-pesa/<int:id>/", eliminar_pesa, name="eliminar_pesa"),
    path("editar-pesa/<int:id>/", editar_pesa, name="editar_pesa"),
]




   

usuarios/urls.py
from django.urls import path
from usuarios import views
from django.contrib.auth.views import LogoutView

app_name = "usuarios"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("perfil/editar/", views.editar_perfil, name="editar_perfil"),
    path("perfil/editar/password/", views.CambiarPassword.as_view(), name="cambiar_password"),
    path("logout/", LogoutView.as_view(template_name="usuarios/logout.html"), name="logout"),
]    

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User

class DatosExtra(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="avatares", default='avatars/default-avatar.jpg', blank=True, null=True)
    

    def __str__(self):
        return self.user.username

usuarios/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

class FormularioDeCreacionDeUsuario(UserCreationForm):
    username = forms.CharField(label="username")
    email = forms.EmailField()
    password1 = forms.CharField(label="Contrasenia", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir Contrasenia", widget=forms.PasswordInput)
    first_name = forms.CharField(label="Nombre")
    last_name = forms.CharField(label="Apellido") 

    class meta:
        model = User
        fields = ["username", "email", "first_name", "last_name", "password1", "password2"]
        help_texts = {key: "" for key in fields}

class FormularioEdicionPerfil(UserChangeForm):
    email = forms.EmailField(label="Email")
    first_name = forms.CharField(label="Nombre")
    last_name = forms.CharField(label="Apellido")
    password = None 
    avatar = forms.ImageField(required=False)

    class Meta():
        model = User
        fields = ["email", "first_name", "last_name", "avatar"] 

usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.contrib.auth import authenticate, login as django_login
from usuarios.forms import FormularioDeCreacionDeUsuario, FormularioEdicionPerfil
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from usuarios.models import DatosExtra

def login(request):

    formulario = AuthenticationForm()

    if request.method =="POST":
        formulario = AuthenticationForm(request, data=request.POST)
        if formulario.is_valid():
            usuario = formulario.get_user()

            django_login(request, usuario)

            DatosExtra.objects.get_or_create(user=usuario)

            return redirect("inicio:inicio")

    return render(request, "usuarios/login.html", {"form": formulario})


def register(request):

    formulario = FormularioDeCreacionDeUsuario()
    if request.method == "POST":
        formulario = FormularioDeCreacionDeUsuario(request.POST)
        if formulario.is_valid():
            user = formulario.save()
           
            DatosExtra.objects.get_or_create(user=user, avatar='avatars/default-avatar.jpg')

            return redirect("usuarios:login")

    return render(request, "usuarios/register.html", {"form": formulario})

@login_required
def editar_perfil(request):
    datos_extra = request.user.datosextra
    formulario = FormularioEdicionPerfil(instance=request.user, initial={"avatar": datos_extra.avatar})

    if request.method == "POST":
        formulario = FormularioEdicionPerfil(request.POST, request.FILES, instance=request.user)
        if formulario.is_valid():
            new_avatar = formulario.cleaned_data.get("avatar")
            
            if new_avatar:
                datos_extra.avatar = new_avatar
            datos_extra.save()

            formulario.save()

            return redirect("inicio:inicio")


    return render(request, "usuarios/editar_perfil.html", {"form": formulario})

class CambiarPassword(LoginRequiredMixin, PasswordChangeView):
    template_name = "usuarios/cambiar_password.html"
    success_url = reverse_lazy("usuarios:editar_perfil")

usuarios/templates/usuarios/cambiar_password.html
{% extends "base.html" %}

{% block title_head %}
Cambiar Password
{% endblock title_head %}

{% block h1_header %}
Cambiar Password de {{request.user.username}}
{% endblock h1_header %}

{% block main %}

<form action={% url "usuarios:cambiar_password" %} method="POST">
{% csrf_token %}

    {{form}}
    <input type="submit" value="Cambiar">
    
</form>

{% endblock main %}

usuarios/templates/usuarios/editar_perfil.html
{% extends "base.html" %}

{% block title_head %}
Editar Perfil
{% endblock title_head %}

{% block h1_header %}
Editar Perfil {{request.user.username}}
{% endblock h1_header %}

{% block main %}

<form action={% url "usuarios:editar_perfil" %} method="POST" enctype="multipart/form-data">
{% csrf_token %}

    {{form}}
    <input type="submit" value="Editar">
    
</form>
<p> 
    <a href={% url "usuarios:cambiar_password" %}>Cambiar password</a>
</p>

{% endblock main %}

usuarios/templates/usuarios/login.html
{% extends "base.html" %}

{% block title_head %}
Inicio de sesion
{% endblock title_head %}

{% block h1_header %}
Inicio de sesion
{% endblock h1_header %}

{% block main %}

<form action={% url "usuarios:login" %} method="POST">
{% csrf_token %}

    {{form}}
    <input type="submit" value="Iniciar sesion">
    
</form>

{% endblock main %}

usuarios/templates/usuarios/logout.html
{% extends "base.html" %}

{% block title_head %}
Cerrar sesion
{% endblock title_head %}

{% block h1_header %}
Cerraste sesion correctamente!
{% endblock h1_header %}

{% block main %}

{% endblock main %}

usuarios/templates/usuarios/register.html
{% extends "base.html" %}

{% block title_head %}
Registro
{% endblock title_head %}

{% block h1_header %}
Registro
{% endblock h1_header %}

{% block main %}

<form action={% url "usuarios:register" %} method="POST">
{% csrf_token %}

    {{form}}
    <input type="submit" value="Registrarse">
    
</form>

{% endblock main %}